google/gemma-2-2b:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 5
  lora_rank: 64
  lora_alpha: 64
  lora_dropout: 0.1

Qwen/Qwen2.5-3B-Instruct:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 1
  lora_rank: 128
  lora_alpha: 128
  lora_dropout: 0.1

microsoft/Phi-3.5-mini-instruct:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 1
  lora_rank: 128
  lora_alpha: 128
  lora_dropout: 0.1

# google/gemma-2b:
#   per_device_train_batch_size: 1
#   gradient_accumulation_steps: 8
#   num_train_epochs: 1
#   lora_rank: 128
#   lora_alpha: 128
#   lora_dropout: 0.1

google/gemma-7b:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 1
  lora_rank: 128
  lora_alpha: 128
  lora_dropout: 0.1
