name: Publish Docker Image

on:
  push:
    branches:
      - main

permissions:
    contents: read
    packages: write
    actions: read
    security-events: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest    
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
      - name: Checkout code
        uses: actions/checkout@v4        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2        
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Get current date and Time
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H%M%S')"
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.date.outputs.date }}